### ISSUE TITLE
Links to r2c.dev are no longer resolvable

### ISSUE THREAD

**Issue by joek-rippling** [semgrep/semgrep-docs#1475]
I came across some pages such as https://semgrep.dev/docs/semgrep-supply-chain/overview/#transitive-dependencies-and-reachability-analysis where they link to 

```Markdown
### Further reading
[Software supply chain security is hard](https://r2c.dev/blog/2022/software-supply-chain-security-is-hard/)
[The best free, open-source supply-chain security tool? The lockfile](https://r2c.dev/blog/2022/the-best-free-open-source-supply-chain-tool-the-lockfile/)
```

r2c.dev -> DNS_PROBE_FINISHED_NXDOMAIN

I'm guessing all of these should be rebased to semgrep.dev, when I do this the links are still valid.

**Comment by s-santillan** [comment]
Thank you. Fixed in https://github.com/semgrep/semgrep-docs/pull/1476.
